/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.teamrocket.boxing;

public class BrunosBox {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new BrunosBox().getGreeting());
    }
}
