/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.teamrocket.boxing;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        BrunosBox classUnderTest = new BrunosBox();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
